# Generated by Django 5.2.3 on 2025-07-26 00:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survivorPool', '0006_alter_pick_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='is_win',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pick',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date published'),
        ),
    ]
