# Generated by Django 5.2.7 on 2026-05-25 03:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survivorPool', '0009_team_current_week_team_game_time_team_is_home_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='publication_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
