# Generated by Django 5.2.7 on 2026-05-25 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survivorPool', '0010_alter_pick_publication_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_year', models.IntegerField()),
                ('week', models.IntegerField()),
                ('game_time', models.DateTimeField(blank=True, null=True)),
                ('home_spread', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('away_spread', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('home_moneyline', models.IntegerField(blank=True, null=True)),
                ('away_moneyline', models.IntegerField(blank=True, null=True)),
                ('home_is_favorite', models.BooleanField(default=False)),
                ('away_is_favorite', models.BooleanField(default=False)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='survivorPool.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='survivorPool.team')),
            ],
            options={
                'ordering': ['season_year', 'week', 'game_time'],
                'unique_together': {('season_year', 'week', 'home_team', 'away_team')},
            },
        ),
    ]
