# Generated by Django 5.2.7 on 2026-05-25 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survivorPool', '0012_chat_weeklock_pick_missed_seasonsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at', 'id']},
        ),
    ]
