# Generated by Django 5.2.14 on 2026-09-13 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survivorPool', '0013_alter_chatmessage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('user', 'User'), ('weekly_lock_summary', 'Weekly final summary')], default='user', max_length=32),
        ),
        migrations.AlterField(
            model_name='pick',
            name='missed_deadline',
            field=models.BooleanField(default=False, help_text='Auto-assigned loss when no pick was made before the final weekly kickoff.'),
        ),
    ]
